apiVersion: v2
appVersion: 0.1.11
dependencies:
- name: common
  repository: https://charts.bitnami.com/bitnami/
  version: 1.6.1
description: Kubernetes cluster visualiser and graphical explorer
home: https://github.com/benc-uk/kubeview
icon: https://raw.githubusercontent.com/benc-uk/kubeview/master/web/client/public/favicon.png
maintainers:
- email: sebastien.prudhomme@gmail.com
  name: sebastien-prudhomme
name: kubeview
version: 2.3.0
